# Generated by Django 4.2.10 on 2024-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
                ("is_admin", models.BooleanField(default=False)),
                ("isBaned", models.BooleanField(default=False)),
            ],
        ),
    ]
