# Generated by Django 4.2.10 on 2024-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="isBaned",
            new_name="is_baned",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
